In [210]:
import pandas as pd 
import numpy as np

In [211]:
pd.options.mode.chained_assignment = None # default='warn'

In [212]:
df1 = pd.read_csv('MarketBusketClient.csv', sep=';', encoding='utf-8-sig') 
df1

,Телефон_new,Группа3,Количество,Дата
0,49574954-56524849545119,ИГРУШКИ ДЛЯ РАЗВИТИЯ МАЛЫШЕЙ,1,21.08.2017 17:05
1,51534957-48525550515032,ДЕТСКАЯ ОДЕЖДА (7-16 лет),3,10.07.2017 15:32
2,55515349-57484951525673,КОНСТРУКТОРЫ,1,31.08.2017 16:53
3,55525757-49565652494875,АКСЕССУАРЫ,1,07.08.2017 13:28
4,55545455-55555653564971,КОЛЯСКИ,1,24.08.2017 23:37
...,...,...,...,...
146010,57505454-53495350565496,ПОДГУЗНИКИ,5,03.07.2017 16:19
146011,57535051-57555156485395,МЯГКИЕ ИГРУШКИ,1,24.08.2017 15:07
146012,57545253-57515750515193,МОЛОКООТСОСЫ,1,11.07.2017 14:47
146013,57545349-48565651515597,"ДЕТСКАЯ МЕБЕЛЬ, МАТРАСЫ",1,03.07.2017 19:31
146014,57555555-55564848524890,ИГРУШКИ ДЛЯ ДЕВОЧЕК,1,04.07.2017 12:52

In [213]:
data = pd.read_csv('filtered_dataВыкупленныеКлиенты.csv', sep=';', encoding='utf-8-sig') 
data

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,21.08.2017 17:05,23.08.2017 00:00,5349589_TR,Доставлен,5 215,5 215,Магазины,Безналичная,Москва,ИГРУШКИ,...,49,1,1,21.08.2017 00:00,49574954-56524849545119,NaN,гость,ID9010021097048,ИнтернетДоставка,NaN
1,10.07.2017 15:32,26.07.2017 00:00,5092210_TR,Доставлен,1 096,1 096,Магазины,Безналичная,Челябинск,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,99,1,2,10.07.2017 00:00,51534957-48525550515032,109117_mu10@74.ru,Гость,IDL00033407452,ИнтернетДоставка,NaN
2,10.07.2017 15:32,26.07.2017 00:00,5092210_TR,Доставлен,1 096,1 096,Магазины,Безналичная,Челябинск,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,99,2,1,10.07.2017 00:00,51534957-48525550515032,109117_mu10@74.ru,Гость,IDL00035334856,ИнтернетДоставка,NaN
3,31.08.2017 16:53,13.09.2017 00:00,5411784_ES,Доставлен,1 345,1 345,Магазины,Безналичная,Челябинск,ИГРУШКИ,...,0,1,1,31.08.2017 00:00,55515349-57484951525673,115117_su24@yandex.ru,Елена,IDL00041203755,ИнтернетДоставка,NaN
4,07.08.2017 13:28,09.08.2017 00:00,5247281_TR,Доставлен,362,362,Магазины,Безналичная,Москва,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,...,49,1,1,07.08.2017 00:00,55525757-49565652494875,NaN,Гость,ID10005586250,ИнтернетДоставка,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267496,03.07.2017 16:19,12.07.2017 00:00,5048351_TR,Доставлен,2 094,2 094,Магазины,Безналичная,Иваново,ПОДГУЗНИКИ,...,99,4,2,03.07.2017 00:00,57505454-53495350565496,NaN,гость,IDL00019922250,ИнтернетДоставка,NaN
267497,24.08.2017 15:07,04.09.2017 00:00,5372437_TR,Доставлен,498,498,Магазины,Безналичная,Санкт-Петербург,ИГРУШКИ,...,99,1,1,24.08.2017 00:00,57535051-57555156485395,NaN,Гость,ID10010945654,ИнтернетДоставка,NaN
267498,11.07.2017 14:47,20.07.2017 00:00,5098837_TR,Доставлен,6 319,6 319,Магазины,Безналичная,Клин (Клинский район),ТОВАРЫ ДЛЯ КОРМЛЕНИЯ,...,49,1,1,11.07.2017 00:00,57545253-57515750515193,NaN,гость,ID9010022579149,ИнтернетДоставка,NaN
267499,03.07.2017 19:31,05.07.2017 00:00,5050771_TR,Доставлен,11 088,11 088,Магазины,Безналичная,Красногорск (Красногорский район),КРУПНОГАБАРИТНЫЙ ТОВАР,...,99,1,1,03.07.2017 00:00,57545349-48565651515597,NaN,гость,IDL00030521048,ИнтернетДоставка,NaN
267500,04.07.2017 12:52,06.07.2017 00:00,5054959_TR,Доставлен,748,748,Магазины,Безналичная,Железнодорожный (Московская область район),ИГРУШКИ,...,99,1,1,04.07.2017 00:00,57555555-55564848524890,NaN,гость,IDL00045582250,ИнтернетДоставка,NaN

In [187]:
dt = dt[dt["Телефон_new"] != "0"] 
dt

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,3,1,30.06.2017 00:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051334048,ИнтернетДоставка,NaN
1,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,4,1,30.06.2017 00:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00051367351,ИнтернетДоставка,NaN
2,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,7,1,30.06.2017 00:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00007611755,ИнтернетДоставка,NaN
3,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,1,1,30.06.2017 00:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00014478250,ИнтернетДоставка,NaN
4,01.07.2017 00:00,06.07.2017 00:00,5031788_TR,Доставлен,1 634,1 634,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,9,1,30.06.2017 00:00,55574948-52495050484877,116117_tu17@mail.ru,Татьяна,IDL00001209351,ИнтернетДоставка,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267686,31.08.2017 23:42,14.09.2017 00:00,5413126_TR,Доставлен,2 336,2 336,Магазины,Безналичная,Ростов-на-Дону,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",...,99,2,1,31.08.2017 00:00,55575349-53505051515379,97117_au17@yandex.ru,Аня,IDL00052147048,ИнтернетДоставка,NaN
267687,31.08.2017 23:42,14.09.2017 00:00,5413126_TR,Доставлен,2 336,2 336,Магазины,Безналичная,Ростов-на-Дону,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",...,99,5,1,31.08.2017 00:00,55575349-53505051515379,97117_au17@yandex.ru,Аня,IDL00006230553,ИнтернетДоставка,NaN
267688,31.08.2017 23:42,14.09.2017 00:00,5413126_TR,Доставлен,2 336,2 336,Магазины,Безналичная,Ростов-на-Дону,ДЕТСКОЕ ПИТАНИЕ,...,99,1,3,31.08.2017 00:00,55575349-53505051515379,97117_au17@yandex.ru,Аня,ID4516250,ИнтернетДоставка,NaN
267689,31.08.2017 23:42,14.09.2017 00:00,5413126_TR,Доставлен,2 336,2 336,Магазины,Безналичная,Ростов-на-Дону,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",...,99,3,1,31.08.2017 00:00,55575349-53505051515379,97117_au17@yandex.ru,Аня,IDL00029279351,ИнтернетДоставка,NaN
267690,31.08.2017 23:42,14.09.2017 00:00,5413126_TR,Доставлен,2 336,2 336,Магазины,Безналичная,Ростов-на-Дону,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",...,99,4,1,31.08.2017 00:00,55575349-53505051515379,97117_au17@yandex.ru,Аня,IDL00029281957,ИнтернетДоставка,NaN

### Количество подкатегорий Группы2. Будут использоваться в качестве названий колонок витрины для Market Basket.

In [214]:
columns = np.unique(data["Группа2"].values) 
print(columns)

['ДЕТСКОЕ ПИТАНИЕ' 'ЖЕНСКИЕ ШТУЧКИ' 'ИГРУШКИ' 'КАНЦТОВАРЫ, КНИГИ, ДИСКИ'
 'КОСМЕТИКА/ГИГИЕНА' 'КРУПНОГАБАРИТНЫЙ ТОВАР' 'ОБУВЬ' 'ПОДГУЗНИКИ'
 'СОПУТСТВУЮЩИЕ ТОВАРЫ' 'ТЕКСТИЛЬ, ТРИКОТАЖ' 'ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА'
 'ТОВАРЫ ДЛЯ ЖИВОТНЫХ' 'ТОВАРЫ ДЛЯ КОРМЛЕНИЯ']

In [215]:
data["Группа2"].value_counts()

ТЕКСТИЛЬ, ТРИКОТАЖ           56325
ИГРУШКИ                      52757
ДЕТСКОЕ ПИТАНИЕ              39708
ПОДГУЗНИКИ                   29264
КОСМЕТИКА/ГИГИЕНА            26597
ТОВАРЫ ДЛЯ КОРМЛЕНИЯ         16016
КРУПНОГАБАРИТНЫЙ ТОВАР       15286
КАНЦТОВАРЫ, КНИГИ, ДИСКИ     15137
ОБУВЬ                        10164
ТОВАРЫ ДЛЯ ЖИВОТНЫХ           4305
ЖЕНСКИЕ ШТУЧКИ                1134
СОПУТСТВУЮЩИЕ ТОВАРЫ           431
ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА      377
Name: Группа2, dtype: int64

### Рассмотрим чеки. Собрать из них словарь для индексов.

In [216]:
data["Телефон_new"].value_counts()

55575054-49514952535572    164
55574957-50484954535578    162
55575051-52505648555677    152
55575454-49525557515373    146
55575448-56545652485376    140
                          ...
55574851-49484857565078      1
55574954-52495756555179      1
55575555-51515051545770      1
55574851-50485451535771      1
55575048-52554849575177      1
Name: Телефон_new, Length: 65928, dtype: int64

In [217]:
checks = np.array(data["Телефон_new"]) 
checks = np.unique(checks) 

print(len(checks)) 
print(checks)

65928
['49574954-56524849545119' '51534957-48525550515032'
 '55515349-57484951525673' ... '57545253-57515750515193'
 '57545349-48565651515597' '57555555-55564848524890']

In [218]:
checks_loc = {key: i for i, key in enumerate(checks)}

### Создаем витрину с колонками Market Basket.

In [219]:
MB = pd.DataFrame(columns=columns)

### Функция: добавлеет новой строки в таблицу, которая заполнена нулями

In [220]:
def add_row(df): 
    temp = pd.DataFrame(0, index=[i for i in checks], columns=columns) 
    df = df.append(temp, ignore_index=False, sort=False) 
    return df

In [221]:
MB = add_row(MB) 
MB = MB.reset_index() 
MB = MB.rename(columns={"index": "КЛИЕНТ"}) 

MB

,КЛИЕНТ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,49574954-56524849545119,0,0,0,0,0,0,0,0,0,0,0,0,0
1,51534957-48525550515032,0,0,0,0,0,0,0,0,0,0,0,0,0
2,55515349-57484951525673,0,0,0,0,0,0,0,0,0,0,0,0,0
3,55525757-49565652494875,0,0,0,0,0,0,0,0,0,0,0,0,0
4,55545455-55555653564971,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65923,57505454-53495350565496,0,0,0,0,0,0,0,0,0,0,0,0,0
65924,57535051-57555156485395,0,0,0,0,0,0,0,0,0,0,0,0,0
65925,57545253-57515750515193,0,0,0,0,0,0,0,0,0,0,0,0,0
65926,57545349-48565651515597,0,0,0,0,0,0,0,0,0,0,0,0,0
65927,57555555-55564848524890,0,0,0,0,0,0,0,0,0,0,0,0,0

In [222]:
MB1 = MB[MB['КЛИЕНТ'] == '0'] 
MB1

Empty DataFrame
Columns: [КЛИЕНТ, ДЕТСКОЕ ПИТАНИЕ, ЖЕНСКИЕ ШТУЧКИ, ИГРУШКИ, КАНЦТОВАРЫ, КНИГИ, ДИСКИ, КОСМЕТИКА/ГИГИЕНА, КРУПНОГАБАРИТНЫЙ ТОВАР, ОБУВЬ, ПОДГУЗНИКИ, СОПУТСТВУЮЩИЕ ТОВАРЫ, ТЕКСТИЛЬ, ТРИКОТАЖ, ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА, ТОВАРЫ ДЛЯ ЖИВОТНЫХ, ТОВАРЫ ДЛЯ КОРМЛЕНИЯ]
Index: []

### Добавление товаров. Построчное добавление количества товара в чек

In [223]:
for i in range(0, 267501): 
    check = data["Телефон_new"][i] 
    j = checks_loc[check] 
    MB[data["Группа2"][i]][j] = MB[data["Группа2"][i]][j] + data["КоличествоПроданоКлиенту"][i]

In [227]:
MB

,КЛИЕНТ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,49574954-56524849545119,0,0,1,0,0,0,0,0,0,0,0,0,0
1,51534957-48525550515032,0,0,0,0,0,0,0,0,0,3,0,0,0
2,55515349-57484951525673,0,0,1,0,0,0,0,0,0,0,0,0,0
3,55525757-49565652494875,0,0,0,0,0,0,0,0,0,0,0,0,1
4,55545455-55555653564971,0,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65923,57505454-53495350565496,0,0,0,0,0,0,0,5,0,0,0,0,0
65924,57535051-57555156485395,0,0,1,0,0,0,0,0,0,0,0,0,0
65925,57545253-57515750515193,0,0,0,0,0,0,0,0,0,0,0,0,1
65926,57545349-48565651515597,0,0,0,0,0,1,0,0,0,0,0,0,0
65927,57555555-55564848524890,0,0,1,0,0,0,0,0,0,0,0,0,0

In [228]:
MB.to_csv('MBClient.csv', index=False, sep=';', encoding='utf-8-sig')

In [229]:
MB

,КЛИЕНТ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,49574954-56524849545119,0,0,1,0,0,0,0,0,0,0,0,0,0
1,51534957-48525550515032,0,0,0,0,0,0,0,0,0,3,0,0,0
2,55515349-57484951525673,0,0,1,0,0,0,0,0,0,0,0,0,0
3,55525757-49565652494875,0,0,0,0,0,0,0,0,0,0,0,0,1
4,55545455-55555653564971,0,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65923,57505454-53495350565496,0,0,0,0,0,0,0,5,0,0,0,0,0
65924,57535051-57555156485395,0,0,1,0,0,0,0,0,0,0,0,0,0
65925,57545253-57515750515193,0,0,0,0,0,0,0,0,0,0,0,0,1
65926,57545349-48565651515597,0,0,0,0,0,1,0,0,0,0,0,0,0
65927,57555555-55564848524890,0,0,1,0,0,0,0,0,0,0,0,0,0

### Написать

In [230]:
import itertools 

#data = pd.read_csv('MarketBusketFinal.csv', sep=';', encoding='utf-8-sig') 
MB = pd.read_csv('MBClient.csv', sep=';', encoding='utf-8-sig')

In [231]:
MB

,КЛИЕНТ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,49574954-56524849545119,0,0,1,0,0,0,0,0,0,0,0,0,0
1,51534957-48525550515032,0,0,0,0,0,0,0,0,0,3,0,0,0
2,55515349-57484951525673,0,0,1,0,0,0,0,0,0,0,0,0,0
3,55525757-49565652494875,0,0,0,0,0,0,0,0,0,0,0,0,1
4,55545455-55555653564971,0,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65923,57505454-53495350565496,0,0,0,0,0,0,0,5,0,0,0,0,0
65924,57535051-57555156485395,0,0,1,0,0,0,0,0,0,0,0,0,0
65925,57545253-57515750515193,0,0,0,0,0,0,0,0,0,0,0,0,1
65926,57545349-48565651515597,0,0,0,0,0,1,0,0,0,0,0,0,0
65927,57555555-55564848524890,0,0,1,0,0,0,0,0,0,0,0,0,0

In [232]:
params = ["support", "confidence", "lift", "expected confidence"] 
res = pd.DataFrame(columns=params)

In [233]:
rows = [' + '.join(i) for i in itertools.permutations(columns, 2)] 
pairs = list(itertools.permutations(columns, 2))

In [234]:
print("Так выглядит список кобминаций, их " + str(len(rows)) + ", ниже приведён пример:\n") 
print(rows[1:5])

Так выглядит список кобминаций, их 156, ниже приведён пример:

['ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ', 'ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ', 'ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА', 'ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР']

In [235]:
temp = pd.DataFrame(0, index=[i for i in rows], columns=params) 

res = res.append(temp, ignore_index=False, sort=False) 
res = res.reset_index() 
res = res.rename(columns={"index": "Пара"}) 
res

,Пара,support,confidence,lift,expected confidence
0,ДЕТСКОЕ ПИТАНИЕ + ЖЕНСКИЕ ШТУЧКИ,0,0,0,0
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,0,0,0,0
2,"ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0,0,0,0
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,0,0,0,0
4,ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР,0,0,0,0
...,...,...,...,...,...
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,0,0,0,0
152,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + СОПУТСТВУЮЩИЕ ТОВАРЫ,0,0,0,0
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",0,0,0,0
154,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,0,0,0,0
155,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТОВАРЫ ДЛЯ ЖИВОТНЫХ,0,0,0,0

### Функции для рассчёта показателей 

1. Support 
2. Confidence 
3. Expected confidence 
4. Lift - данный показатель можно выразить через 2 другие функции, но для экономии вычислительного времени просто будем использовать полученные результаты и деление

In [236]:
def support(a, b, df):
    counter = 0
    for i in range(0, len(df)):
        if df[a][i] > 0 and df[b][i] > 0:
            counter += 1
    return counter/len(df)

In [237]:
def confidence(a, b, df):
    counter = 0
    total = 0
    for i in range(0, len(df)):
        if df[a][i] > 0:
            total += 1 
            if df[b][i] > 0:
                counter += 1
    return counter/total

In [238]:
def expconf(a, b, df):
    counter = 0
    for i in range(0, len(df)):
        if df[b][i] > 0:
            counter += 1
    return counter/len(df)

### Итоговая таблица

In [239]:
for i in range(0, len(pairs)): 
    sup = support(pairs[i][0], pairs[i][1], MB) 
    conf = confidence(pairs[i][0], pairs[i][1], MB) 
    exconf = expconf(pairs[i][0], pairs[i][1], MB) 
    lift = (conf / exconf) 
    res['support'][i] = sup 
    res['confidence'][i] = conf 
    res['expected confidence'][i] = exconf 
    res['lift'][i] = lift

In [240]:
res

,Пара,support,confidence,lift,expected confidence
0,ДЕТСКОЕ ПИТАНИЕ + ЖЕНСКИЕ ШТУЧКИ,0.00145613,0.01298,2.62498,0.00494479
1,ДЕТСКОЕ ПИТАНИЕ + ИГРУШКИ,0.0260284,0.232017,0.692585,0.335002
2,"ДЕТСКОЕ ПИТАНИЕ + КАНЦТОВАРЫ, КНИГИ, ДИСКИ",0.0072655,0.0647647,1.00584,0.0643884
3,ДЕТСКОЕ ПИТАНИЕ + КОСМЕТИКА/ГИГИЕНА,0.0310187,0.276501,2.15806,0.128125
4,ДЕТСКОЕ ПИТАНИЕ + КРУПНОГАБАРИТНЫЙ ТОВАР,0.00876714,0.0781504,0.4235,0.184535
...,...,...,...,...,...
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ПОДГУЗНИКИ,0.0457014,0.388323,1.58542,0.244934
152,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + СОПУТСТВУЮЩИЕ ТОВАРЫ,0.000637059,0.00541307,1.13654,0.00476277
153,"ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕКСТИЛЬ, ТРИКОТАЖ",0.0321715,0.27336,1.1595,0.235757
154,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,0.000819075,0.00695966,2.03927,0.00341281
155,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ + ТОВАРЫ ДЛЯ ЖИВОТНЫХ,0.00200218,0.0170125,0.892994,0.0190511

In [241]:
res.to_csv('MBClientFinal.csv', index=False, sep=';', encoding='utf-8-sig')